#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Syncfusion.Data.Resource.String.library_name = global::App1.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int scale_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int scale_out = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060028
			public const int DBAddressText = 2131099688;
			
			// aapt resource value: 0x7f060019
			public const int Vraag1 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int Vraag2 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int Vraag3 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int Vraag4 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int Vraag5 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int Vraag6 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int Vraag7 = 2131099679;
			
			// aapt resource value: 0x7f060024
			public const int address_text = 2131099684;
			
			// aapt resource value: 0x7f060007
			public const int axisLayout = 2131099655;
			
			// aapt resource value: 0x7f06002a
			public const int bottom_labels = 2131099690;
			
			// aapt resource value: 0x7f06000e
			public const int btnCreateDB = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int btnCreateTable = 2131099663;
			
			// aapt resource value: 0x7f060020
			public const int btnDatabase = 2131099680;
			
			// aapt resource value: 0x7f060014
			public const int btnDelete = 2131099668;
			
			// aapt resource value: 0x7f060026
			public const int btnDeleteAddress = 2131099686;
			
			// aapt resource value: 0x7f060011
			public const int btnGetData = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int btnGetDataByID = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int btnInstert = 2131099664;
			
			// aapt resource value: 0x7f060025
			public const int btnSaveAddress = 2131099685;
			
			// aapt resource value: 0x7f060021
			public const int btnSaveLocation = 2131099681;
			
			// aapt resource value: 0x7f060030
			public const int btnSearch = 2131099696;
			
			// aapt resource value: 0x7f060027
			public const int btnShowLocation = 2131099687;
			
			// aapt resource value: 0x7f060018
			public const int btnTask = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int btnUpdate = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int chartAreaLayout = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int chartTitle = 2131099649;
			
			// aapt resource value: 0x7f06002b
			public const int content = 2131099691;
			
			// aapt resource value: 0x7f060006
			public const int dataMarkerLayout = 2131099654;
			
			// aapt resource value: 0x7f060023
			public const int get_address_button = 2131099683;
			
			// aapt resource value: 0x7f060003
			public const int gridLineLayout = 2131099651;
			
			// aapt resource value: 0x7f06002c
			public const int gridLinesLayout = 2131099692;
			
			// aapt resource value: 0x7f06000c
			public const int iconView = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int label = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int legendHeader = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int legendItemsLayout = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int legendScrollView = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int legendViewGroup = 2131099656;
			
			// aapt resource value: 0x7f060022
			public const int location_text = 2131099682;
			
			// aapt resource value: 0x7f060000
			public const int rootLayout = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int seriesLayout = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int stripLinesLayout = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int textView1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int textView2 = 2131099670;
			
			// aapt resource value: 0x7f060031
			public const int textView3 = 2131099697;
			
			// aapt resource value: 0x7f06002d
			public const int thumbLayout = 2131099693;
			
			// aapt resource value: 0x7f060029
			public const int top_labels = 2131099689;
			
			// aapt resource value: 0x7f060017
			public const int txtTask = 2131099671;
			
			// aapt resource value: 0x7f06002e
			public const int txtTaskID = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int txtTaskId = 2131099695;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chart_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_legend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Database = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InsertTaskLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Note = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int range_navigator_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RemoveTask_Layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SearchLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int UpdateTaskLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Vraag1_Layout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int ApplicationName = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Hello = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int Vraag1 = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int library_name = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int q = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int quarter = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int w = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int week = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
